export const AllBusesdata=([
    // From Hyderabad
{ from: "Hyderabad", to: "Bangalore", type: "AC", name: "Vovo", price: 2500, imageUrl: "https://assets.volvo.com/is/image/VolvoInformationTechnologyAB/blue-bus?qlt=82&wid=1024&ts=1660212095501&dpr=off&fit=constrain",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Hyderabad", to: "Bangalore", type: "AC", name: "Luxury", price: 2800, imageUrl: "https://www.tempotravellerdelhi.co.in/assets/images/bus-rent.webp",PickupLocations:["kukattapali"],dropLocations:["ramakrishnanager"] },
{ from: "Hyderabad", to: "Bangalore", type: "Non-AC", name: "Ordinary", price: 1500, imageUrl: "https://www.abhibus.com/blog/wp-content/uploads/2023/06/TSRTC-Launches-Vehicle-Tracking-System-in-Ordinary-Buses-e1686730483919.jpg",PickupLocations:["miyapur"],dropLocations:["shivanager"] },
{ from: "Hyderabad", to: "Bangalore", type: "Non-AC", name: "Ordinary", price: 1500, imageUrl: "https://www.abhibus.com/blog/wp-content/uploads/2023/06/TSRTC-Launches-Vehicle-Tracking-System-in-Ordinary-Buses-e1686730483919.jpg",PickupLocations:["miyapur"],dropLocations:["shivanager"] },
{ from: "Hyderabad", to: "Bangalore", type: "Non-AC", name: "Ordinary", price: 1500, imageUrl: "https://www.abhibus.com/blog/wp-content/uploads/2023/06/TSRTC-Launches-Vehicle-Tracking-System-in-Ordinary-Buses-e1686730483919.jpg",PickupLocations:["miyapur"],dropLocations:["shivanager"] },
{ from: "Hyderabad", to: "Pune", type: "AC", name: "Vovo", price: 2600, imageUrl: "https://assets.volvo.com/is/image/VolvoInformationTechnologyAB/blue-bus?qlt=82&wid=1024&ts=1660212095501&dpr=off&fit=constrain",PickupLocations:["kphb"],dropLocations:["harswadi"] },
{ from: "Hyderabad", to: "Pune", type: "AC", name: "Luxury", price: 2900, imageUrl: "https://www.tempotravellerdelhi.co.in/assets/images/bus-rent.webp",PickupLocations:["kondapur"],dropLocations:["Techmahendra bustop"] },
{ from: "Hyderabad", to: "Pune", type: "Non-AC", name: "Ordinary", price: 1700, imageUrl: "https://www.abhibus.com/blog/wp-content/uploads/2023/06/TSRTC-Launches-Vehicle-Tracking-System-in-Ordinary-Buses-e1686730483919.jpg",PickupLocations:["kukattapali"],dropLocations:["punebustop"]},
{ from: "Hyderabad", to: "Pune", type: "Non-AC", name: "Ordinary", price: 1700, imageUrl: "https://www.abhibus.com/blog/wp-content/uploads/2023/06/TSRTC-Launches-Vehicle-Tracking-System-in-Ordinary-Buses-e1686730483919.jpg",PickupLocations:["kukattapali"],dropLocations:["punebustop"]},
{ from: "Hyderabad", to: "Pune", type: "Non-AC", name: "Ordinary", price: 1700, imageUrl: "https://www.abhibus.com/blog/wp-content/uploads/2023/06/TSRTC-Launches-Vehicle-Tracking-System-in-Ordinary-Buses-e1686730483919.jpg",PickupLocations:["kukattapali"],dropLocations:["punebustop"]},

// From Bangalore
{ from: "Bangalore", to: "Hyderabad", type: "AC", name: "Vovo", price: 2200, imageUrl: "https://assets.volvo.com/is/image/VolvoInformationTechnologyAB/blue-bus?qlt=82&wid=1024&ts=1660212095501&dpr=off&fit=constrain",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Bangalore", to: "Hyderabad", type: "AC", name: "Luxury", price: 2700, imageUrl: "https://www.tempotravellerdelhi.co.in/assets/images/bus-rent.webp",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Bangalore", to: "Hyderabad", type: "Non-AC", name: "Ordinary", price: 1600, imageUrl: "https://www.abhibus.com/blog/wp-content/uploads/2023/06/TSRTC-Launches-Vehicle-Tracking-System-in-Ordinary-Buses-e1686730483919.jpg",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Bangalore", to: "Hyderabad", type: "Non-AC", name: "Express", price: 1700, imageUrl: "https://www.tsrtc.telangana.gov.in/img/buses/expr092021n.jpg",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Bangalore", to: "Hyderabad", type: "Non-AC", name: "Super express", price: 1800, imageUrl: "https://www.tsrtc.telangana.gov.in/img/buses/expr092021n.jpg",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Bangalore", to: "Pune", type: "AC", name: "Vovo", price: 2400, imageUrl: "https://assets.volvo.com/is/image/VolvoInformationTechnologyAB/blue-bus?qlt=82&wid=1024&ts=1660212095501&dpr=off&fit=constrain",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Bangalore", to: "Pune", type: "AC", name: "Luxury", price: 2900, imageUrl: "https://www.tempotravellerdelhi.co.in/assets/images/bus-rent.webp",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Bangalore", to: "Pune", type: "Non-AC", name: "Ordinary", price: 1700, imageUrl: "https://www.abhibus.com/blog/wp-content/uploads/2023/06/TSRTC-Launches-Vehicle-Tracking-System-in-Ordinary-Buses-e1686730483919.jpg",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Bangalore", to: "Pune", type: "Non-AC", name: "Express", price: 1800, imageUrl: "https://www.tsrtc.telangana.gov.in/img/buses/expr092021n.jpg",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Bangalore", to: "Pune", type: "Non-AC", name: "Super express", price: 1900, imageUrl: "https://www.tsrtc.telangana.gov.in/img/buses/expr092021n.jpg",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },

// From Pune
{ from: "Pune", to: "Hyderabad", type: "AC", name: "Vovo", price: 2400, imageUrl: "https://assets.volvo.com/is/image/VolvoInformationTechnologyAB/blue-bus?qlt=82&wid=1024&ts=1660212095501&dpr=off&fit=constrain",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Pune", to: "Hyderabad", type: "AC", name: "Luxury", price: 2800, imageUrl: "https://www.tempotravellerdelhi.co.in/assets/images/bus-rent.webp",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Pune", to: "Hyderabad", type: "Non-AC", name: "Ordinary", price: 1600, imageUrl: "https://www.abhibus.com/blog/wp-content/uploads/2023/06/TSRTC-Launches-Vehicle-Tracking-System-in-Ordinary-Buses-e1686730483919.jpg",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Pune", to: "Hyderabad", type: "Non-AC", name: "Express", price: 1700, imageUrl: "https://www.tsrtc.telangana.gov.in/img/buses/expr092021n.jpg",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Pune", to: "Hyderabad", type: "Non-AC", name: "Super express", price: 1800, imageUrl: "https://www.tsrtc.telangana.gov.in/img/buses/expr092021n.jpg",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Pune", to: "Bangalore", type: "AC", name: "Vovo", price: 2500, imageUrl: "https://assets.volvo.com/is/image/VolvoInformationTechnologyAB/blue-bus?qlt=82&wid=1024&ts=1660212095501&dpr=off&fit=constrain",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Pune", to: "Bangalore", type: "AC", name: "Luxury", price: 2800, imageUrl: "https://www.tempotravellerdelhi.co.in/assets/images/bus-rent.webp",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Pune", to: "Bangalore", type: "Non-AC", name: "Ordinary", price: 1500, imageUrl: "https://www.abhibus.com/blog/wp-content/uploads/2023/06/TSRTC-Launches-Vehicle-Tracking-System-in-Ordinary-Buses-e1686730483919.jpg",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] },
{ from: "Pune", to: "Bangalore", type: "Non-AC", name: "Express", price: 1600, imageUrl: "https://www.tsrtc.telangana.gov.in/img/buses/expr092021n.jpg" ,PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"]},
{ from: "Pune", to: "Bangalore", type: "Non-AC", name: "Super express", price: 1700, imageUrl: "https://www.tsrtc.telangana.gov.in/img/buses/expr092021n.jpg",PickupLocations: ["kphb phase-1","kphb phase-2", "kphb phase-3"],dropLocations: ["bangalorebustop","marathalli"] }
]);